### ISSUE TITLE
Admin and User View: Background image disappears or loads slowly

### ISSUE THREAD

**Issue by azle** [kmthorn/lyon.19archive#1]
When I initially load the background map as an image it loads fine. However, after adding markers or edits the map either disappears or loads slowly.

**Comment by kmthorn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test](https://trello.com/c/EqUkQ5il/5-test)

**Comment by kmthorn** [comment]
@azle I talked to Franny about this issue. It was recommended for the two of us to contact Reclaim and ask for technical support. Before we do we will most likely need to get permission from Heidi to call as her current Neatline support. When we get back from vacation, we can chat more about next steps to how to approach working with Reclaim through a faculty owned and third-party hosted digital project.

**Comment by azle** [comment]
Omeka Classic Plugin Forum: Neatline static image layer won't show

https://forum.omeka.org/t/neatline-static-image-layer-wont-show/1491/7
