### ISSUE TITLE
Admin: Adding Markers

### ISSUE THREAD

**Issue by azle** [kmthorn/lyon.19archive#2]
When I create a new marker and upload a custom marker image. The image sometimes doesn't load and I would have to delete the marker and create a new one.

**Comment by kmthorn** [comment]
@azle I talked to Franny about this issue. It was recommended for the two of us to contact Reclaim and ask for technical support. Before we do we will most likely need to get permission from Heidi to call as her current Neatline support. When we get back from vacation, we can chat more about next steps to how to approach working with Reclaim through a faculty owned and third-party hosted digital project.

**Comment by azle** [comment]
Resolved when we updated to the new version of the neatline plugin 4/17/18
