### ISSUE TITLE
Admin: Background image and Editing markers

### ISSUE THREAD

**Issue by azle** [kmthorn/lyon.19archive#3]
When I go to edit a marker. Either changing the location or general editing the background map image never loads. However, when the marker is first created the map is visible.

[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":false,"ownerId":false,"dependencies":[]})

**Comment by kmthorn** [comment]
@azle I talked to Franny about this issue. It was recommended for the two of us to contact Reclaim and ask for technical support. Before we do we will most likely need to get permission from Heidi to call as her current Neatline support. When we get back from vacation, we can chat more about next steps to how to approach working with Reclaim through a faculty owned and third-party hosted digital project.

**Comment by azle** [comment]
Resolved when updated to new version of php and nestling plugin.
